In [1]:
import pandas as pd

In [2]:
error = pd.read_csv("German/errors/1000_errors_German")
error

    Unnamed: 0        tn        fp        fn        tp  percentage
0            0  0.000721  0.000000  0.973333  0.025946        0.01
1            1  0.001081  0.000000  0.972973  0.025946        0.02
2            2  0.001081  0.000000  0.972973  0.025946        0.03
3            3  0.001441  0.000000  0.972613  0.025946        0.04
4            4  0.002523  0.000000  0.971532  0.025946        0.05
..         ...       ...       ...       ...       ...         ...
95          95  0.974054  0.025586  0.000000  0.000360        0.96
96          96  0.974054  0.025586  0.000000  0.000360        0.97
97          97  0.974054  0.025586  0.000000  0.000360        0.98
98          98  0.974054  0.025586  0.000000  0.000360        0.99
99          99  0.974054  0.025586  0.000000  0.000360        1.00

[100 rows x 6 columns]

In [13]:
error[error.fn==0.0]

    Unnamed: 0        tn        fp   fn        tp  percentage
89          89  0.974054  0.025225  0.0  0.000721        0.90
90          90  0.974054  0.025586  0.0  0.000360        0.91
91          91  0.974054  0.025586  0.0  0.000360        0.92
92          92  0.974054  0.025586  0.0  0.000360        0.93
93          93  0.974054  0.025586  0.0  0.000360        0.94
94          94  0.974054  0.025586  0.0  0.000360        0.95
95          95  0.974054  0.025586  0.0  0.000360        0.96
96          96  0.974054  0.025586  0.0  0.000360        0.97
97          97  0.974054  0.025586  0.0  0.000360        0.98
98          98  0.974054  0.025586  0.0  0.000360        0.99
99          99  0.974054  0.025586  0.0  0.000360        1.00

In [25]:
best = pd.read_csv("all_cutoffs/entire_best_cutoff.csv")
best.sort_values(by=['corpus'], inplace=True)
best

,Unnamed: 0,Unnamed: 0.1,fp,fn,percentage,delta,corpus,mfw
5,15,56,0.005766,0.003964,0.57,0.3382,Chinese,1000
2,6,48,0.002883,0.003964,0.49,0.2243,English,2000
1,10,64,0.004324,0.009730,0.65,0.3385,French,500
4,26,56,0.002883,0.003964,0.57,0.3040,German,1000
6,4,64,0.002416,0.002953,0.65,0.3955,piperDE,500
0,18,67,0.003311,0.005459,0.68,0.3996,piperEN,1000
3,18,68,0.004592,0.005828,0.69,0.4367,piperFR,500

In [21]:
delta = pd.read_hdf("German/delta/1000_delta_German.h5")
ma = max(delta.cosine)
mi = min(delta.cosine)
rang = ma-mi
# mi + rang*x = 0.2
(0.2 - mi)/rang

0.4202898550724637

In [23]:
alle = pd.read_csv("all_cutoffs/entire_all_cutoff.csv")
alle[alle.corpus=='German']

,Unnamed: 0,Unnamed: 0.1,fp,fn,percentage,delta,corpus,mfw
112,26,56,0.002883,0.003964,0.57,0.3040,German,1000
113,24,53,0.003243,0.003604,0.54,0.2686,German,2000
114,12,48,0.003243,0.004324,0.49,0.2249,German,3000
115,16,42,0.003243,0.005045,0.43,0.1540,German,9000
116,18,44,0.003243,0.005045,0.45,0.1690,German,8000
117,20,44,0.003243,0.005405,0.45,0.1770,German,7000
118,13,49,0.003604,0.003243,0.50,0.2350,German,3000
119,25,54,0.003604,0.003243,0.55,0.2795,German,2000
120,4,46,0.003604,0.003604,0.47,0.1983,German,6000
121,5,46,0.003604,0.003604,0.47,0.1983,German,6000
122,14,46,0.003604,0.003604,0.47,0.2024,German,5000
123,15,46,0.003604,0.003604,0.47,0.2024,German,5000
124,22,62,0.003604,0.003604,0.63,0.3664,German,500
125,23,62,0.003604,0.003604,0.63,0.3664,German,500
126,0,43,0.003604,0.003964,0.44,0.1588,German,10000
127,19,45,0.003964,0.003243,0.46,0.1772,German,8000
128,17,43,0.003964,0.003604,0.44,0.1620,German,9000
129,27,57,0.003964,0.003604,0.58,0.3160,German,1000
130,2,47,0.003964,0.003964,0.48,0.2108,German,4000
131,3,47,0.003964,0.003964,0.48,0.2108,German,4000
132,1,44,0.004324,0.002883,0.45,0.1665,German,10000
133,21,45,0.004324,0.003243,0.46,0.1856,German,7000
134,10,69,0.006486,0.006486,0.70,0.4790,German,100
135,11,69,0.006486,0.006486,0.70,0.4790,German,100
136,6,74,0.007207,0.009369,0.75,0.5075,German,50
137,7,75,0.007928,0.006847,0.76,0.5232,German,50
138,8,86,0.013694,0.018739,0.87,0.7291,German,10
139,9,87,0.015495,0.015135,0.88,0.7484,German,10